
import type { Blueprint } from '../types';

/**
 * Represents an internal link with metadata for intelligent matching
 */
export interface InternalLink {
    title: string;
    url: string;
    keywords: string[]; // For relevance matching
    category?: string;
}

/**
 * Niche-specific link collections
 * Each niche has its own curated list of internal links
 */
export interface LinkRepository {
    food: InternalLink[];
    tech: InternalLink[];
    gaming: InternalLink[];
    diy: InternalLink[];
    health: InternalLink[];
    travel: InternalLink[];
    lifestyle: InternalLink[];
    finance: InternalLink[];
    education: InternalLink[];
    entertainment: InternalLink[];
}

/**
 * Maps blueprint types to their primary niche
 */
const BLUEPRINT_TO_NICHE_MAP: Record<Blueprint, keyof LinkRepository> = {
    'recipe': 'food',
    'roundup': 'tech', // Default, can be overridden
    'review': 'tech',  // Default, can be overridden
    'howto': 'diy',    // Default, can be overridden
};

/**
 * Comprehensive link repository with niche-specific collections
 */

// Keep this intentionally empty.
// Platform links (postgeniuspro.com) must never be injected into user-generated articles.
const COMMON_LINKS: InternalLink[] = [];



const FOODJOT_URLS = [
    "https://foodjot.blog/",
    "https://foodjot.blog/crispy-air-fryer-broccoli-florets/",
    "https://foodjot.blog/homemade-freeze-dried-candy-diy/",
    "https://foodjot.blog/keto-mug-cake-recipe-in-5-minutes/",
    "https://foodjot.blog/easy-instant-pot-seafood-boil-recipe/",
    "https://foodjot.blog/vegan-cashew-cream-sauce-pasta/",
    "https://foodjot.blog/french-walnut-cake/",
    "https://foodjot.blog/mario-mushroom-recipes/",
    "https://foodjot.blog/girl-dinner-hack-gourmet-boards/",
    "https://foodjot.blog/ninja-creami-recipes/",
    "https://foodjot.blog/mediterranean-diet-recipes/",
    "https://foodjot.blog/10-minute-sauteed-zucchini/",
    "https://foodjot.blog/crispy-banana-blossom-fish-recipe/",
    "https://foodjot.blog/sleepy-girl-mocktail/",
    "https://foodjot.blog/crispy-baked-salmon-fillets/",
    "https://foodjot.blog/charcuterie-board-ideas/",
    "https://foodjot.blog/zucchini-fritters-recipe/",
    "https://foodjot.blog/refreshing-lemon-ricotta-pancakes/",
    "https://foodjot.blog/whipped-avocado-toast/",
    "https://foodjot.blog/ceviche-peruano-recipe/",
    "https://foodjot.blog/grilled-halloumi-recipe/",
    "https://foodjot.blog/simple-syrup-recipe/",
    "https://foodjot.blog/moroccan-couscous-recipe/",
    "https://foodjot.blog/tortellini-soup/",
    "https://foodjot.blog/homemade-poke-bowl-recipe/",
    "https://foodjot.blog/cottage-cheese-pancakes/",
    "https://foodjot.blog/fudgy-brownie-recipe/",
    "https://foodjot.blog/mango-ice-cream-recipe/",
    "https://foodjot.blog/ramen-recipe/",
    "https://foodjot.blog/noodle-soup-recipe/",
    "https://foodjot.blog/overnight-oats-recipe/",
    "https://foodjot.blog/easy-nachos-recipe/",
    "https://foodjot.blog/easy-homemade-flatbread-recipe/",
    "https://foodjot.blog/naan-pizza-recipe/",
    "https://foodjot.blog/how-to-boil-eggs-perfectly/",
    "https://foodjot.blog/how-to-cook-zucchini/",
    "https://foodjot.blog/crispy-buffalo-wings/",
    "https://foodjot.blog/pumpkin-soup-recipe/",
    "https://foodjot.blog/cinnamon-rolls/",
    "https://foodjot.blog/cornbread-recipe-buttery-moist-chili-side/",
    "https://foodjot.blog/sloppy-joe-recipe/",
    "https://foodjot.blog/creamy-potato-soup/",
    "https://foodjot.blog/puerto-rican-pernil-recipe/",
    "https://foodjot.blog/ultimate-pot-roast-recipe/",
    "https://foodjot.blog/easy-zucchini-recipe/",
    "https://foodjot.blog/perfectly-crispy-french-fries/",
    "https://foodjot.blog/coffee-ice-cream-chocolate-sauce/",
    "https://foodjot.blog/carrot-juice-recipe-glowing-skin/",
    "https://foodjot.blog/hummus-recipe/",
    "https://foodjot.blog/blueberry-muffin-recipe/",
    "https://foodjot.blog/teelhead-trout-recipe/",
    "https://foodjot.blog/frittata-recipe/",
    "https://foodjot.blog/chow-chow-recipe/",
    "https://foodjot.blog/coconut-balls-recipe/",
    "https://foodjot.blog/must-try-recipes-food-jot/",
    "https://foodjot.blog/red-currants-honey-lemon-recipe/",
    "https://foodjot.blog/crab-dip-recipe/",
    "https://foodjot.blog/angel-food-cake-recipe/",
    "https://foodjot.blog/classic-italian-lasagna-recipe/",
    "https://foodjot.blog/bearnaise-sauce-recipe/",
    "https://foodjot.blog/10-best-recipes-meat-seafood-desserts/",
    "https://foodjot.blog/perfect-homemade-donuts/",
    "https://foodjot.blog/ultimate-cheese-board-guide/",
    "https://foodjot.blog/sushi-bake-recipe/",
    "https://foodjot.blog/best-garlic-bread-recipe/",
    "https://foodjot.blog/baked-ziti-recipe/",
    "https://foodjot.blog/pesto-recipe-homemade-basil-sauce/",
    "https://foodjot.blog/best-fluffy-pancake-recipe/",
    "https://foodjot.blog/vegetarian-recipes-10-healthy-easy-meat-free-meals/",
    "https://foodjot.blog/reuben-sandwich-recipe/",
    "https://foodjot.blog/grilled-cheese-sandwich/",
    "https://foodjot.blog/hearty-lentil-soup-recipe/",
    "https://foodjot.blog/seafood-risotto-recipe/",
    "https://foodjot.blog/champagne-orange-ice-cream-cake/",
    "https://foodjot.blog/spicy-thai-curry-recipes/",
    "https://foodjot.blog/date-caramel-recipe-natures-candy/",
    "https://foodjot.blog/hollandaise-sauce-recipe/",
    "https://foodjot.blog/griddled-fruit-honey-drizzle/",
    "https://foodjot.blog/blackstone-recipes-burgers-to-breakfasts/",
    "https://foodjot.blog/classic-baked-beans-recipe/",
    "https://foodjot.blog/candied-fruit-fritters-recipe-2/",
    "https://foodjot.blog/homemade-turkey-sausage-recipe/",
    "https://foodjot.blog/aip-meatloaf/",
    "https://foodjot.blog/vegan-mushroom-recipe/",
    "https://foodjot.blog/1920s-chocolate-cake-recipe/",
    "https://foodjot.blog/cheez-it-peanut-butter-chocolate-recipe/",
    "https://foodjot.blog/caldo-de-pollo-recipe/",
    "https://foodjot.blog/ultimate-traeger-recipes/",
    "https://foodjot.blog/pokemon-sleep-recipes/",
    "https://foodjot.blog/top-10-blackstone-griddle-recipes/",
    "https://foodjot.blog/classic-baked-beans/",
    "https://foodjot.blog/how-long-should-you-boil-eggs/",
    "https://foodjot.blog/classic-bolognese-sauce-recipe/",
    "https://foodjot.blog/authentic-carnitas-recipe/",
    "https://foodjot.blog/tobiko-creamy-pasta-recipe/",
    "https://foodjot.blog/bibimbap-recipe-korean-rice-bowl/",
    "https://foodjot.blog/perfect-gyoza-recipe/",
    "https://foodjot.blog/classic-carbonara-recipe/",
    "https://foodjot.blog/carnitas-recipe-juicy-and-flavorful/",
    "https://foodjot.blog/crepes-smoked-salmon-lemon-sauce/",
    "https://foodjot.blog/hachis-parmentier-recipe/",
    "https://foodjot.blog/best-alfredo-sauce-recipe/",
    "https://foodjot.blog/haddock-fritters-a-la-scandinave/",
    "https://foodjot.blog/fritada-de-mariscos-2/",
    "https://foodjot.blog/classic-meatloaf-recipe/",
    "https://foodjot.blog/soft-sugar-cookies/",
    "https://foodjot.blog/tanghulu-recipe/",
    "https://foodjot.blog/top-recipes-on-food-jot-blog/",
    "https://foodjot.blog/dubai-chocolate-bar-recipe/",
    "https://foodjot.blog/grilled-beef-steaks-yogurt-sauce/",
    "https://foodjot.blog/taco-soup-recipe/",
    "https://foodjot.blog/juicy-baked-chicken-breast-creamy-sauce/",
    "https://foodjot.blog/grilled-haddock-with-cream-sauce/",
    "https://foodjot.blog/honey-ice-cream-recipe/",
    "https://foodjot.blog/chocolate-ice-cream-with-orange-sauce/",
    "https://foodjot.blog/the-ultimate-cheese-ball-recipe/",
    "https://foodjot.blog/easy-banana-bread-recipe-perfectly-moist-delicious/",
    "https://foodjot.blog/dried-fruit-cake-recipe/",
    "https://foodjot.blog/ice-cream-waffles/",
    "https://foodjot.blog/traditional-homemade-waffles/",
    "https://foodjot.blog/seafood-skewers-with-saffron-rice/",
    "https://foodjot.blog/thanksgiving-chicken-recipe/",
    "https://foodjot.blog/perfect-mashed-potatoes-recipe/",
    "https://foodjot.blog/classic-french-toast-recipe/",
    "https://foodjot.blog/christmas-chex-mix-recipe/",
    "https://foodjot.blog/garlic-parmesan-chicken-pasta-recipe/",
    "https://foodjot.blog/hungarian-cake-with-cottage-cheese-gateau/",
    "https://foodjot.blog/crab-brulee-recipe/",
    "https://foodjot.blog/cottage-cheese-recipes-10-delicious-ways-to-enjoy-it/",
    "https://foodjot.blog/lyon-style-fried-tripe-recipe/",
    "https://foodjot.blog/grilled-pork-fillets-mustard-marinade/",
    "https://foodjot.blog/veal-medallions-butterfly-style/",
    "https://foodjot.blog/easy-banana-bread-recipe/",
    "https://foodjot.blog/classic-creamy-mac-and-cheese-recipe/",
    "https://foodjot.blog/chocolate-chip-cookie-recipe/",
    "https://foodjot.blog/cottage-cheese-recipes/",
    "https://foodjot.blog/homemade-white-chocolate-recipe/",
    "https://foodjot.blog/vegetarian-stuffed-bell-peppers-quinoa/",
    "https://foodjot.blog/manhattan-and-saxon-hamburgers/",
    "https://foodjot.blog/master-the-art-of-venison-gigot-domino/",
    "https://foodjot.blog/seafood-gratin-recipe/",
    "https://foodjot.blog/grilled-gambas-and-prawns-with-moorish-sauce/",
    "https://foodjot.blog/rabbit-galantine/",
    "https://foodjot.blog/how-to-make-gluten-free-fried-rice/",
    "https://foodjot.blog/how-to-make-tabasco-sauce-recipe/",
    "https://foodjot.blog/perfect-gougeres-french-cheese-puffs-made-easy/",
    "https://foodjot.blog/buckwheat-galettes-with-ham-and-cream/",
    "https://foodjot.blog/dark-chocolate-lava-cakes/",
    "https://foodjot.blog/goujonettes-de-sole-orly-recipe/",
    "https://foodjot.blog/how-to-make-gratin-dauphinois/",
    "https://foodjot.blog/gnocchi-alla-romana-a-classic-italian-comfort-food/",
    "https://foodjot.blog/portuguese-bean-gratin-recipe/",
    "https://foodjot.blog/hungarian-goulash-recipe/",
    "https://foodjot.blog/traditional-garbure-recipe/",
    "https://foodjot.blog/fromage-blanc-with-fresh-herbs/",
    "https://foodjot.blog/fruit-and-nut-energy-bites/",
    "https://foodjot.blog/swiss-roll-cake-gateau-roule/",
    "https://foodjot.blog/frisee-salad-with-bacon-2/",
    "https://foodjot.blog/oriental-meatballs-recipe/",
    "https://foodjot.blog/refreshing-homemade-gazpacho-recipe/",
    "https://foodjot.blog/french-fries-recipe-2/",
    "https://foodjot.blog/cheese-fondue-surprise/",
    "https://foodjot.blog/favorite-dessert-recipes/",
    "https://foodjot.blog/caramel-ice-cream-recipe/",
    "https://foodjot.blog/gnocchi-a-la-parisienne-recipe/",
    "https://foodjot.blog/italian-pasta/",
    "https://foodjot.blog/healthy-breakfast-recipes/",
    "https://foodjot.blog/fluffy-waffles-with-custard-sauce/",
    "https://foodjot.blog/celebrate-honey-deuce-cocktail-recipe/",
    "https://foodjot.blog/gateau-alsacien-recipe/",
    "https://foodjot.blog/garbure-traditional-french-soup/",
    "https://foodjot.blog/crispy-fried-prawns-with-broccoli/",
    "https://foodjot.blog/gennoise-tutti-frutti-recipe/",
    "https://foodjot.blog/rabbit-galantine-classic-french-dish/",
    "https://foodjot.blog/fruits-armagnac-batter/",
    "https://foodjot.blog/seafood-paella-skewers/",
    "https://foodjot.blog/delicious-buckwheat-pancakes-with-egg-and-bacon-recipe/",
    "https://foodjot.blog/buckwheat-galettes/",
    "https://foodjot.blog/fresh-fruits-martinique/",
    "https://foodjot.blog/candied-fruit-fritters-recipe/",
    "https://foodjot.blog/fromage-blanc-with-fine-herbs-a-delightful-french-recipe/",
    "https://foodjot.blog/hearty-garbure-recipe/",
    "https://foodjot.blog/authentic-piedmontese-fritto-misto-recipe/",
    "https://foodjot.blog/fritada-de-mariscos/",
    "https://foodjot.blog/frisee-salad-with-bacon/",
    "https://foodjot.blog/authentic-fritto-misto-alla-piemontese-recipe/",
    "https://foodjot.blog/lemon-waffles/",
    "https://foodjot.blog/caramel-waffles-recipe/",
    "https://foodjot.blog/fricatelles-orientales-recipe/",
    "https://foodjot.blog/raspberry-mousseline/",
    "https://foodjot.blog/french-fries-recipe/",
    "https://foodjot.blog/cardinal-strawberries/",
    "https://foodjot.blog/english-style-strawberries/",
    "https://foodjot.blog/cinnamon-fougasse/",
    "https://foodjot.blog/fondue-savoyarde/",
    "https://foodjot.blog/chocolate-fondue-recipe/",
    "https://foodjot.blog/fondue-bourguignonne/",
    "https://foodjot.blog/seafood-fondue/",
    "https://foodjot.blog/surprise-cheese-fondue/",
    "https://foodjot.blog/seafood-fondue-recipe/",
    "https://foodjot.blog/creamy-mango-mousse-cake/",
    "https://foodjot.blog/pineapple-and-caramel-cake/",
    "https://foodjot.blog/martinican-rice-cake-gateau-de-riz-martiniquais/",
    "https://foodjot.blog/viral-food-trends-2025/",
    "https://foodjot.blog/chocolate-fondant/",
    "https://foodjot.blog/frozen-meringue-cake-a-la-cevenole-recipe/",
    "https://foodjot.blog/iranian-style-lamb-fricassee/",
    "https://foodjot.blog/easy-one-pot-chicken-and-vegetable-stew-recipe/",
    "https://foodjot.blog/bohemian-goulash-with-three-meats/",
    "https://foodjot.blog/leg-of-lamb-braised-in-braillouse-style/",
    "https://foodjot.blog/hearty-beef-stew-slow-cooker-winter/",
    "https://foodjot.blog/10-must-try-recipes-food-jot-blog/",
    "https://foodjot.blog/one-pan-chicken-and-vegetables/",
    "https://foodjot.blog/french-onion-soup-with-chicken-breasts/",
    "https://foodjot.blog/daves-hot-chicken-recipe/",
    "https://foodjot.blog/honey-garlic-chicken-recipe/",
    "https://foodjot.blog/chicken-fricassee/",
    "https://foodjot.blog/chicken-fricassee-with-white-wine/",
    "https://foodjot.blog/one-pan-lemon-herb-sheet-pan-dinner/",
    "https://foodjot.blog/japanese-style-chicken-fondue/",
    "https://foodjot.blog/honey-garlic-fermented-carrots/",
    "https://foodjot.blog/budget-friendly-vegan-meal-prep/",
    "https://foodjot.blog/roasted-cauliflower/",
    "https://foodjot.blog/10-irresistible-puff-pastry-dessert-recipes/",
    "https://foodjot.blog/fondue-with-fruit-coulis-and-liqueur/",
    "https://foodjot.blog/the-ultimate-guide-to-fondue/",
    "https://foodjot.blog/alsatian-cherry-cake-recipe/",
    "https://foodjot.blog/tiktok-tobiko-pasta-recipe/",
    "https://foodjot.blog/juicy-baked-chicken-thighs/",
    "https://foodjot.blog/canned-sardine-recipes/",
    "https://foodjot.blog/hot-honey-popcorn-recipe/",
    "https://foodjot.blog/grilled-fruit-healthy-dessert/",
    "https://foodjot.blog/hot-honey-shrimp/",
    "https://foodjot.blog/make-ahead-egg-sandwiches/",
    "https://foodjot.blog/salisbury-steak-no-bake-desserts/",
    "https://foodjot.blog/moist-banana-bread-recipe/",
    "https://foodjot.blog/harira-marocaine-recette/",
    "https://foodjot.blog/best-chicken-tagine-recipe/",
    "https://foodjot.blog/moroccan-chicken-tagine-recipe/",
    "https://foodjot.blog/vegan-tzatziki-sauce-recipe/",
    "https://foodjot.blog/gold-curry-challenge/",
    "https://foodjot.blog/whole30-italian-meatballs-zucchini-noodles/",
    "https://foodjot.blog/healthy-kimchi-jjigae-recipe/",
    "https://foodjot.blog/homemade-ketchup-without-sugar/",
    "https://foodjot.blog/copycat-chilis-southwest-egg-rolls/",
    "https://foodjot.blog/forget-store-bought-tabasco-sauce/",
    "https://foodjot.blog/daves-hot-chicken-recipe-2/",
    "https://foodjot.blog/doenjang-jjigae-fermented-skate/",
    "https://foodjot.blog/sopa-de-mondongo-tripe-soup/",
    "https://foodjot.blog/budget-friendly-vegan-black-bean-burgers/",
    "https://foodjot.blog/easy-30-minute-moroccan-plant-based-meals/",
    "https://foodjot.blog/fall-off-the-bone-ribs/",
    "https://foodjot.blog/tzatziki-sauce-recipe/",
    "https://foodjot.blog/homemade-pesto-sauce/",
    "https://foodjot.blog/sausage-pasta-recipe/",
    "https://foodjot.blog/gratin-languedocien-recipe/",
    "https://foodjot.blog/french-green-beans-maitre-dhotel/",
    "https://foodjot.blog/canes-sauce-recipe/",
    "https://foodjot.blog/teriyaki-sauce-recipe/",
    "https://foodjot.blog/greek-lamb-souvlaki-skewers/",
    "https://foodjot.blog/air-fryer-honey-butter-chips/",
    "https://foodjot.blog/ube-crinkle-cookies-cream-cheese/",
    "https://foodjot.blog/beef-stroganoff-recipe/",
    "https://foodjot.blog/vietnamese-pho-recipe/",
    "https://foodjot.blog/5-minute-avocado-salsa-recipe/",
    "https://foodjot.blog/harengs-a-la-boulangere-recipe/",
    "https://foodjot.blog/birria-tacos-recipe/",
    "https://foodjot.blog/mediterranean-smash-burger-sauce/",
    "https://foodjot.blog/french-roasted-lamb-leg-recipe/",
    "https://foodjot.blog/french-onion-soup-with-gruyere-toast/",
    "https://foodjot.blog/homemade-kfc-style-fried-chicken/",
    "https://foodjot.blog/roasted-cauliflower-steaks-chimichurri/",
    "https://foodjot.blog/homemade-chimichurri-sauce/",
    "https://foodjot.blog/authentic-tiramisu-recipe/",
    "https://foodjot.blog/brisket-recipe/",
    "https://foodjot.blog/french-toast-recipe/",
    "https://foodjot.blog/bruschetta-recipe/",
    "https://foodjot.blog/falafel-recipe/",
    "https://foodjot.blog/homemade-ricotta-cheese/",
    "https://foodjot.blog/katsu-curry-recipe/",
    "https://foodjot.blog/harissa-sauce-recipe/",
    "https://foodjot.blog/brazilian-feijoada-recipe/",
    "https://foodjot.blog/street-food-around-the-world-20-irresistible-dishes-food-jot-likes/",
    "https://foodjot.blog/australian-meat-pie-recipe/",
    "https://foodjot.blog/low-fodmap-fermented-garlic-misir-wat/",
    "https://foodjot.blog/chimichurri-sauce-recipe/",
    "https://foodjot.blog/best-electric-pressure-cookers-for-beginners/",
    "https://foodjot.blog/low-calorie-dinner-recipes-under-500-calories/",
    "https://foodjot.blog/sugar-free-popsicles-recipe/",
    "https://foodjot.blog/healthy-air-fryer-chicken-wings/",
    "https://foodjot.blog/keto-breakfast-ideas-for-busy-mornings/",
    "https://foodjot.blog/no-bake-chocolate-energy-balls-recipe/",
    "https://foodjot.blog/best-air-fryers-for-small-kitchens-the-2025-buyers-guide/",
    "https://foodjot.blog/best-induction-cooktops-for-apartment-living/",
    "https://foodjot.blog/best-non-stick-pans-without-toxic-coatings-2025/",
    "https://foodjot.blog/best-meat-thermometers-for-steak-guide-2025/",
    "https://foodjot.blog/best-cold-brew-coffee-makers-guide-2025/",
    "https://foodjot.blog/best-vacuum-sealers-for-meat-storage-guide-2025/",
    "https://foodjot.blog/best-salad-spinners-guide-2025/",
    "https://foodjot.blog/best-spice-racks-small-kitchens/",
    "https://foodjot.blog/best-woks-for-asian-cooking/",
    "https://foodjot.blog/best-french-press-coffee-makers-rich-flavor/",
    "https://foodjot.blog/best-chefs-knives-for-home-cooks-2025/",
    "https://foodjot.blog/electric-salad-spinners-top-picks-crisp-greens/",
    "https://foodjot.blog/digital-kitchen-scales-accurate-baking/",
    "https://foodjot.blog/affordable-pasta-makers-fresh-pasta-home/",
    "https://foodjot.blog/fondue-pots-for-cheese-and-chocolate-nights/",
    "https://foodjot.blog/best-dehydrators-homemade-snacks/",
    "https://foodjot.blog/best-stand-mixers-for-home-bakers-2025/",
    "https://foodjot.blog/best-seller-slushie-machines-amazon/",
    "https://foodjot.blog/best-compact-blenders-2025/",
    "https://foodjot.blog/fullstar-vegetable-chopper-review/",
    "https://foodjot.blog/top-santoku-knives-precise-cutting/",
    "https://foodjot.blog/best-smart-electric-kettles-temperature-control/",
    "https://foodjot.blog/affordable-espresso-machines-home-baristas/",
    "https://foodjot.blog/sushi-making-kits-for-beginners/",
    "https://foodjot.blog/best-electric-griddles-2025/",
    "https://foodjot.blog/best-bamboo-steamer-dim-sum/",
    "https://foodjot.blog/best-smart-toasters-2025/",
    "https://foodjot.blog/best-propane-gas-grills-2025/",
    "https://foodjot.blog/best-bread-machines-2025-buying-guide/",
    "https://foodjot.blog/6-best-cold-press-juicers-2025/",
    "https://foodjot.blog/microwave-convection-oven-air-fryer-2025/",
    "https://foodjot.blog/best-smart-cooking-robots-2025/",
    "https://foodjot.blog/best-outdoor-pizza-ovens-2025/",
    "https://foodjot.blog/best-waffle-makers-2025/",
    "https://foodjot.blog/best-nugget-ice-makers-2025/",
    "https://foodjot.blog/best-air-fryer-toaster-oven-combo/",
    "https://foodjot.blog/best-sous-vide-machines-2025/",
    "https://foodjot.blog/best-chocolate-fountains/",
    "https://foodjot.blog/best-cedar-grilling-planks-salmon/",
    "https://foodjot.blog/best-knife-sharpeners/",
    "https://foodjot.blog/best-immersion-blender/",
    "https://foodjot.blog/best-food-processors-home-cooks/",
    "https://foodjot.blog/best-yogurt-makers/",
    "https://foodjot.blog/best-tabasco-substitutes/",
    "https://foodjot.blog/best-sustainable-caviar-brands/",
    "https://foodjot.blog/best-mini-donut-maker-2025/",
    "https://foodjot.blog/best-indoor-pizza-ovens/",
    "https://foodjot.blog/best-small-rice-cookers-2025/",
    "https://foodjot.blog/on-the-border-signature-queso/",
    "https://foodjot.blog/carote-14-piece-nonstick-pots-pans/",
    "https://foodjot.blog/homemade-ice-cream-soft-serve-maker/",
    "https://foodjot.blog/dash-deluxe-shaved-ice-maker-review/",
    "https://foodjot.blog/best-bread-makers-2025/",
    "https://foodjot.blog/best-cheese-slicers-2025-review/",
    "https://foodjot.blog/best-mason-jars-2025-review/",
    "https://foodjot.blog/best-nonstick-ceramic-cookware-sets-2025/",
    "https://foodjot.blog/best-burr-coffee-grinders-2025/",
    "https://foodjot.blog/best-keurig-coffee-makers-2025/",
    "https://foodjot.blog/best-citrus-juicers-2025/",
    "https://foodjot.blog/best-pumpkin-cocottes/",
    "https://foodjot.blog/simple-skillet-lemon-herb-chicken/",
    "https://foodjot.blog/hearty-french-style-mushroom-stew/",
    "https://foodjot.blog/easy-hotdog-roll-ups/",
    "https://foodjot.blog/crispy-japanese-tonkatsu-pork-cutlets/",
    "https://foodjot.blog/blue-cheese-and-dried-cranberry-tossed-salad/",
    "https://foodjot.blog/balsamic-caprese-grilled-steak-recipe/",
    "https://foodjot.blog/homemade-apple-cider-syrup/",
    "https://foodjot.blog/savory-hibachi-zucchini-stir-fry/",
    "https://foodjot.blog/flavorful-lemongrass-vietnamese-pork-chop/",
    "https://foodjot.blog/real-chinese-all-purpose-stir-fry-sauce/",
    "https://foodjot.blog/classic-home-style-beef-stroganoff/",
    "https://foodjot.blog/easy-garlic-butter-crab-legs/",
    "https://foodjot.blog/irresistible-mini-philly-cheesesteaks/",
    "https://foodjot.blog/mamaws-chicken-and-rice-casserole/",
    "https://foodjot.blog/slow-cooker-barbequed-beef-ribs/",
    "https://foodjot.blog/best-slow-cookers-2025-review/",
    "https://foodjot.blog/best-glass-air-fryers-review/",
    "https://foodjot.blog/best-ninja-portable-blenders/",
    "https://foodjot.blog/best-electric-salt-and-pepper-grinders/",
    "https://foodjot.blog/best-stainless-steel-mixing-bowls-with-lids-2025/",
    "https://foodjot.blog/best-electric-mason-jar-sealers/",
    "https://foodjot.blog/best-apple-peelers-for-effortless-prep/",
    "https://foodjot.blog/decadent-no-bake-double-chocolate-cheesecake/",
    "https://foodjot.blog/flavorful-homemade-cajun-spiced-sauce/",
    "https://foodjot.blog/cafe-tropical-burrito-recipe/",
    "https://foodjot.blog/heartwarming-italian-sunday-sauce/",
    "https://foodjot.blog/brendas-apple-and-pomegranate-crisp/",
    "https://foodjot.blog/crispy-apple-pie-egg-rolls/",
    "https://foodjot.blog/crispy-homemade-tempura-batter/",
    "https://foodjot.blog/classic-braised-beef-recipe/",
    "https://foodjot.blog/my-mums-cranberry-summer-pudding/",
    "https://foodjot.blog/quick-tartar-sauce-recipe/",
    "https://foodjot.blog/easy-classic-cranberry-sauce/",
    "https://foodjot.blog/creamy-alfredo-sauce/",
    "https://foodjot.blog/quick-tartar-sauce-recipe-2/",
    "https://foodjot.blog/homemade-spaghetti-sauce/",
    "https://foodjot.blog/simple-teriyaki-sauce-recipe/",
    "https://foodjot.blog/easy-pizza-sauce/",
    "https://foodjot.blog/best-small-rice-cookers/",
    "https://foodjot.blog/best-electric-jar-openers-effortless-kitchen-convenience/",
    "https://foodjot.blog/easy-one-pan-lemon-herb-roasted-chicken/",
    "https://foodjot.blog/classic-creamy-tuna-salad/",
    "https://foodjot.blog/soothing-moroccan-mint-tea/",
    "https://foodjot.blog/easy-skillet-philly-cheesesteak-hoagies/",
    "https://foodjot.blog/best-air-fryer-toaster-oven-combo-2/",
    "https://foodjot.blog/best-nonstick-cookware-sets/",
    "https://foodjot.blog/best-nespresso-machines/",
    "https://foodjot.blog/best-ninja-creami-ice-cream-maker/",
    "https://foodjot.blog/best-owala-freesip-water-bottle-review/",
    "https://foodjot.blog/best-kitchen-knife-sets/",
    "https://foodjot.blog/ninja-crispi-portable-air-fryer-review/",
    "https://foodjot.blog/easy-delicious-chicken-marsala/",
    "https://foodjot.blog/best-electric-coffee-grinders/",
    "https://foodjot.blog/asian-glazed-salmon-a-quick-flavorful-weeknight-meal/",
    "https://foodjot.blog/gourmia-indoor-pizza-oven-air-fryer-toaster-review/",
    "https://foodjot.blog/carote-17pcs-pots-pans-non-stick-detachable/",
    "https://foodjot.blog/best-food-warming-mats/",
    "https://foodjot.blog/gourmia-toaster-oven-air-fryer-combo-review/",
    "https://foodjot.blog/classic-waffles/",
    "https://foodjot.blog/best-electric-lunch-box-review/",
    "https://foodjot.blog/best-sushi-cutting-machine-review/",
    "https://foodjot.blog/best-burger-press/",
    "https://foodjot.blog/best-stainless-steel-cookware-sets/",
    "https://foodjot.blog/best-hot-dog-and-bun-toasters/",
    "https://foodjot.blog/strawberry-french-toast/",
    "https://foodjot.blog/hearty-turkey-and-vegetable-chili/",
    "https://foodjot.blog/best-electric-herb-grinders-top-picks/",
    "https://foodjot.blog/bbq-salmon-bowls/",
    "https://foodjot.blog/minute-breakfast-burrito/",
    "https://foodjot.blog/copycat-din-tai-fung-cucumber-salad/",
    "https://foodjot.blog/pumpkin-chai-latte-bars/",
    "https://foodjot.blog/slow-cooker-barbecue-ribs/",
    "https://foodjot.blog/thai-coconut-pumpkin-soup/",
    "https://foodjot.blog/a-very-big-pumpkin-layer-cake/",
    "https://foodjot.blog/best-vacuum-sealer-machines/",
    "https://foodjot.blog/five-ingredient-red-curry-chicken/",
    "https://foodjot.blog/beer-glazed-brats-and-sauerkraut/",
    "https://foodjot.blog/old-fashioned-coconut-cream-pie/",
    "https://foodjot.blog/cheap-chicken-noodle-casserole/",
    "https://foodjot.blog/crumbl-style-giant-frosted-sugar-cookies/",
    "https://foodjot.blog/moroccan-lamb-meatballs/",
    "https://foodjot.blog/moroccan-lamb-backstrap/",
    "https://foodjot.blog/best-countertop-double-burner-review/",
    "https://foodjot.blog/best-hot-air-popcorn-poppers/",
    "https://foodjot.blog/best-coffee-makers-review/",
    "https://foodjot.blog/baked-mac-and-cheese/",
    "https://foodjot.blog/best-travel-mugs-top-picks/",
    "https://foodjot.blog/baghrir-pancakes-with-brown-butter-spiced-apples/",
    "https://foodjot.blog/this-surprising-ingredient-makes-the-crispiest-potatoes-ever/",
    "https://foodjot.blog/best-snackle-box-container-reviews/",
    "https://foodjot.blog/campfire-carnitas-recipe/",
    "https://foodjot.blog/enchilada-sauce-classic/",
    "https://foodjot.blog/creamy-chicken-enchiladas/",
    "https://foodjot.blog/lemongrass-chicken-rice-paper-rolls/",
    "https://foodjot.blog/sawdust-pie-bars-a-delightfully/",
    "https://foodjot.blog/best-countertop-microwaves-reviews/",
    "https://foodjot.blog/shakshuka-recipe-easy-traditional/",
    "https://foodjot.blog/lamb-souvlaki/",
    "https://foodjot.blog/easy-baked-tennessee-onions-with-melted-cheese/",
    "https://foodjot.blog/firecracker-chicken-meatballs/",
    "https://foodjot.blog/slow-cooker-chicken-and-salsa/",
    "https://foodjot.blog/delicious-and-easy-cottage-cheese-and-egg-bake/",
    "https://foodjot.blog/best-kitchen-blenders-and-choppers-buying-guide/",
    "https://foodjot.blog/oysters-rockefeller/",
    "https://foodjot.blog/seven-layer-gelatin-salad/",
    "https://foodjot.blog/teriyaki-baked-pork-chops/",
    "https://foodjot.blog/best-toasters-perfect-toast/",
    "https://foodjot.blog/best-mini-electric-hot-pots-review/",
    "https://foodjot.blog/sauteed-green-beans-with-garlic/",
    "https://foodjot.blog/lamb-koftas-with-yoghurt-dressing/",
    "https://foodjot.blog/candied-jalapenos/",
    "https://foodjot.blog/how-to-make-hot-beverages-with-an-electric-kettle/",
    "https://foodjot.blog/i-tried-6-chocolate-ice-creams-and-there-was-1-clear-winner/",
    "https://foodjot.blog/best-nut-milk-makers/",
    "https://foodjot.blog/chicken-in-creamy-mustard-sauce/",
    "https://foodjot.blog/meet-colombian-hot-dogs/",
    "https://foodjot.blog/this-foolproof-way-to-deep-fry-chicken/",
    "https://foodjot.blog/best-small-freezers/",
    "https://foodjot.blog/best-glass-air-fryers-review-2/",
    "https://foodjot.blog/easy-homemade-banana-bread-recipe/",
    "https://foodjot.blog/best-henckels-knife-sets/",
    "https://foodjot.blog/best-under-cabinet-kitchen-tv/",
    "https://foodjot.blog/best-electric-lunch-boxes/",
    "https://foodjot.blog/shrimp-with-broccoli-in-garlic-sauce/",
    "https://foodjot.blog/best-chicken-shredder-tool/",
    "https://foodjot.blog/maple-glazed-ham-recipe/",
    "https://foodjot.blog/5-ingredient-pork-chop-dinner/",
    "https://foodjot.blog/best-sourdough-starter-kits/",
    "https://foodjot.blog/one-pan-baked-butter-chicken/",
    "https://foodjot.blog/classic-chocolate-chip-cookies/",
    "https://foodjot.blog/homemade-ratatouille-recipe/",
    "https://foodjot.blog/betty-crocker-cheese-dreams/",
    "https://foodjot.blog/best-apple-peelers-effortless-prep/",
    "https://foodjot.blog/miso-roasted-japanese-eggplant/",
    "https://foodjot.blog/classic-chicken-chasseur-recipe/",
    "https://foodjot.blog/best-air-fryers-review-guide/",
    "https://foodjot.blog/best-chamber-vacuum-sealers/",
    "https://foodjot.blog/caprese-appetizer-skewers/",
    "https://foodjot.blog/thai-grilled-chicken-gai-yang/",
    "https://foodjot.blog/zucchini-cheese-muffin-slab/",
    "https://foodjot.blog/best-electric-kitchen-composters/",
    "https://foodjot.blog/hamburger-soup-iv/",
    "https://foodjot.blog/chinese-all-purpose-stir-fry-sauce/",
    "https://foodjot.blog/best-commercial-salad-spinner-guide/",
    "https://foodjot.blog/hawaiian-chicken-salad-recipe/",
    "https://foodjot.blog/best-smart-mugs-perfect-temperature-drinks/",
    "https://foodjot.blog/holiday-stuffed-sweet-potato/",
    "https://foodjot.blog/chimichurri-butter-recipe/",
    "https://foodjot.blog/char-siu-pork-recipe/",
    "https://foodjot.blog/best-electric-lunch-box/",
    "https://foodjot.blog/best-electric-hand-mixers-review/",
    "https://foodjot.blog/authentic-thai-red-duck-curry/",
    "https://foodjot.blog/best-grain-and-rice-cooker/"
];

const FOOD_LINKS: InternalLink[] = [
    ...FOODJOT_URLS.map(url => {
        // Extract slug from URL
        const slug = url.replace("https://foodjot.blog/", "").replace(/\/$/, "");

        // Create title from slug (or use "Home" for the root URL)
        const title = slug
            ? slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
            : "Food Jot Home";

        // Create keywords from slug
        const keywords = slug
            ? slug.split('-')
            : ["food", "recipes", "cooking"];

        return {
            title,
            url,
            keywords,
            category: 'food'
        };
    }),
    // High-Authority Recipe/Guide URLs
    { title: "BBC Good Food Recipes", url: "https://www.bbcgoodfood.com/recipes", keywords: ["bbc", "recipes", "cooking", "uk"] },

    { title: "Food Network Recipes", url: "https://www.foodnetwork.com/recipes", keywords: ["food network", "recipes", "cooking"] },
    { title: "Epicurious Recipes", url: "https://www.epicurious.com/recipes", keywords: ["epicurious", "recipes", "gourmet"] },
    { title: "Serious Eats Recipes", url: "https://www.seriouseats.com/recipes", keywords: ["serious eats", "recipes", "cooking science"] },
    { title: "AllRecipes", url: "https://www.allrecipes.com/recipes/", keywords: ["allrecipes", "recipes", "home cooking"] },
    { title: "NY Times Cooking", url: "https://cooking.nytimes.com/", keywords: ["nytimes", "cooking", "recipes"] },
    { title: "Bon Appétit Recipes", url: "https://www.bonappetit.com/recipes", keywords: ["bon appetit", "recipes", "cooking"] },
    { title: "Guardian Food Recipes", url: "https://www.theguardian.com/food/series/recipes", keywords: ["guardian", "recipes", "uk"] },
    { title: "Taste of Home", url: "https://www.tasteofhome.com/recipes/", keywords: ["taste of home", "recipes", "comfort food"] },
    { title: "The Kitchn Recipes", url: "https://www.thekitchn.com/collection/recipes", keywords: ["kitchn", "recipes", "cooking"] },
    { title: "Delish Recipes", url: "https://www.delish.com/", keywords: ["delish", "recipes", "easy cooking"] },
    { title: "Jamie Oliver Recipes", url: "https://www.jamieoliver.com/recipes/", keywords: ["jamie oliver", "recipes", "uk chef"] },
    { title: "Martha Stewart Recipes", url: "https://www.marthastewart.com/1503463/recipes", keywords: ["martha stewart", "recipes", "cooking"] },
    { title: "The Spruce Eats", url: "https://www.thespruceeats.com/recipes-4162684", keywords: ["spruce eats", "recipes", "cooking"] },
    { title: "Eating Well Recipes", url: "https://www.eatingwell.com/recipes/", keywords: ["eating well", "healthy", "recipes"] },
    { title: "Betty Crocker Recipes", url: "https://www.bettycrocker.com/recipes", keywords: ["betty crocker", "recipes", "baking"] },
    { title: "Cook's Illustrated", url: "https://www.cooksillustrated.com/recipes", keywords: ["cooks illustrated", "recipes", "tested"] },
    { title: "Cooking Light", url: "https://www.cookinglight.com/recipes", keywords: ["cooking light", "healthy", "recipes"] },
    { title: "The Pioneer Woman", url: "https://www.thepioneerwoman.com/food-cooking/recipes/", keywords: ["pioneer woman", "recipes", "comfort food"] },
    { title: "BBC Food Recipes", url: "https://www.bbc.co.uk/food/recipes", keywords: ["bbc", "food", "recipes", "uk"] },
    { title: "Yummly Recipes", url: "https://www.yummly.com/recipes", keywords: ["yummly", "recipes", "personalized"] },
    { title: "Food & Wine Recipes", url: "https://www.foodandwine.com/recipes", keywords: ["food wine", "recipes", "gourmet"] },
    { title: "Minimalist Baker", url: "https://www.minimalistbaker.com/recipes/", keywords: ["minimalist baker", "simple", "recipes"] },
    { title: "Sally's Baking Addiction", url: "https://www.sallysbakingaddiction.com/recipes/", keywords: ["sallys baking", "baking", "desserts"] },
    { title: "Nigella Lawson Recipes", url: "https://www.nigella.com/recipes", keywords: ["nigella", "recipes", "uk chef"] },
    { title: "Olive Magazine Recipes", url: "https://www.olivemagazine.com/recipes/", keywords: ["olive", "recipes", "uk"] },
    { title: "Tasting Table Recipes", url: "https://www.tastingtable.com/section/recipes/", keywords: ["tasting table", "recipes", "food culture"] },
    { title: "Eater Recipes", url: "https://www.eater.com/recipes", keywords: ["eater", "recipes", "food news"] },
    { title: "Good Housekeeping Recipes", url: "https://www.goodhousekeeping.com/food-recipes/", keywords: ["good housekeeping", "recipes"] },
    { title: "Fine Cooking Recipes", url: "https://www.finecooking.com/recipes", keywords: ["fine cooking", "recipes", "techniques"] },
    { title: "Great British Chefs", url: "https://www.greatbritishchefs.com/recipes", keywords: ["british chefs", "recipes", "uk"] },
];

const TECH_LINKS: InternalLink[] = [
    ...COMMON_LINKS,
    // Best-Of/Roundup URLs
    { title: "NY Times Wirecutter", url: "https://www.nytimes.com/wirecutter/", keywords: ["wirecutter", "reviews", "best", "products"] },
    { title: "Consumer Reports", url: "https://www.consumerreports.org/cro/index.htm", keywords: ["consumer reports", "reviews", "testing", "ratings"] },
    { title: "Good Housekeeping Reviews", url: "https://www.goodhousekeeping.com/uk/product-reviews/", keywords: ["good housekeeping", "reviews", "products"] },
    { title: "Which? Reviews", url: "https://www.which.co.uk/reviews", keywords: ["which", "reviews", "uk", "consumer"] },
    { title: "Best Products", url: "https://www.bestproducts.com/", keywords: ["best products", "reviews", "shopping"] },
    { title: "TechRadar Best", url: "https://www.techradar.com/news/best", keywords: ["techradar", "best", "tech", "reviews"] },
    { title: "CNET Best", url: "https://www.cnet.com/topics/best/", keywords: ["cnet", "best", "tech", "products"] },
    { title: "T3 Best Products", url: "https://www.t3.com/uk/features/best-products", keywords: ["t3", "best", "products", "tech"] },
    { title: "Digital Trends Best", url: "https://www.digitaltrends.com/best-products/", keywords: ["digital trends", "best", "products"] },
    { title: "PCMag Picks", url: "https://www.pcmag.com/picks", keywords: ["pcmag", "picks", "best", "tech"] },
    { title: "Tom's Guide Best", url: "https://www.tomsguide.com/us/best-products", keywords: ["toms guide", "best", "products"] },
    { title: "Forbes Personal Shopper", url: "https://www.forbes.com/sites/forbes-personal-shopper/", keywords: ["forbes", "shopping", "best"] },
    { title: "Business Insider Guides", url: "https://www.businessinsider.com/guides", keywords: ["business insider", "guides", "best"] },
    { title: "NY Mag Strategist", url: "https://nymag.com/strategist/", keywords: ["strategist", "best", "shopping"] },
    // Single Review URLs
    { title: "CNET Reviews", url: "https://www.cnet.com/reviews/", keywords: ["cnet", "reviews", "tech"] },
    { title: "TechRadar Reviews", url: "https://www.techradar.com/reviews", keywords: ["techradar", "reviews", "tech"] },
    { title: "Tom's Guide Reviews", url: "https://www.tomsguide.com/reviews", keywords: ["toms guide", "reviews"] },
    { title: "PCMag Reviews", url: "https://www.pcmag.com/reviews", keywords: ["pcmag", "reviews", "tech"] },
    { title: "Digital Trends Reviews", url: "https://www.digitaltrends.com/reviews/", keywords: ["digital trends", "reviews"] },
    { title: "RTings", url: "https://www.rtings.com/", keywords: ["rtings", "reviews", "testing", "measurements"] },
    { title: "Trusted Reviews", url: "https://www.trustedreviews.com/", keywords: ["trusted reviews", "uk", "tech"] },
    { title: "Wired Reviews", url: "https://www.wired.com/category/reviews/", keywords: ["wired", "reviews", "tech"] },
    { title: "Engadget Reviews", url: "https://www.engadget.com/reviews/", keywords: ["engadget", "reviews", "tech"] },
    { title: "GSMArena", url: "https://www.gsmarena.com/reviews.php3", keywords: ["gsmarena", "phone", "reviews"] },
    { title: "SoundGuys Reviews", url: "https://www.soundguys.com/reviews/", keywords: ["soundguys", "audio", "reviews"] },
    { title: "Laptop Mag Reviews", url: "https://www.laptopmag.com/reviews", keywords: ["laptop mag", "laptop", "reviews"] },
    { title: "The Verge Reviews", url: "https://www.theverge.com/reviews", keywords: ["verge", "reviews", "tech"] },
    { title: "Android Authority Reviews", url: "https://www.androidauthority.com/reviews/", keywords: ["android authority", "android", "reviews"] },
    { title: "MacRumors Reviews", url: "https://www.macrumors.com/reviews/", keywords: ["macrumors", "apple", "reviews"] },
];

const GAMING_LINKS: InternalLink[] = [
    ...COMMON_LINKS,
    { title: "GameSpot Reviews", url: "https://www.gamespot.com/reviews/", keywords: ["gamespot", "game", "reviews"] },
    { title: "Metacritic", url: "https://www.metacritic.com/", keywords: ["metacritic", "reviews", "scores"] },
    { title: "IGN Reviews", url: "https://www.ign.com/reviews", keywords: ["ign", "game", "reviews"] },
    { title: "Eurogamer Reviews", url: "https://www.eurogamer.net/reviews", keywords: ["eurogamer", "game", "reviews"] },
];

const DIY_LINKS: InternalLink[] = [
    ...COMMON_LINKS,
    // How-To Guide URLs
    { title: "WikiHow", url: "https://www.wikihow.com/", keywords: ["wikihow", "how to", "tutorials", "guides"] },
    { title: "Instructables", url: "https://www.instructables.com/", keywords: ["instructables", "diy", "projects", "how to"] },
    { title: "How-To Geek", url: "https://www.howtogeek.com/", keywords: ["how to geek", "tech", "tutorials"] },
    { title: "MakeUseOf", url: "https://www.makeuseof.com/", keywords: ["makeuseof", "tech", "how to"] },
    { title: "Lifehacker", url: "https://www.lifehacker.com/", keywords: ["lifehacker", "tips", "how to", "productivity"] },
    { title: "Popular Mechanics How-To", url: "https://www.popularmechanics.com/how-to/", keywords: ["popular mechanics", "how to", "diy"] },
    { title: "Family Handyman", url: "https://www.familyhandyman.com/", keywords: ["family handyman", "diy", "home improvement"] },
    { title: "HowStuffWorks", url: "https://www.howstuffworks.com/", keywords: ["howstuffworks", "how to", "science"] },
    { title: "Home Depot DIY", url: "https://www.homedepot.com/c/diy_projects_and_ideas", keywords: ["home depot", "diy", "projects"] },
    { title: "CNET How-To", url: "https://www.cnet.com/how-to/", keywords: ["cnet", "how to", "tech"] },
    { title: "Tom's Guide How-To", url: "https://www.tomsguide.com/how-to/", keywords: ["toms guide", "how to", "tech"] },
    { title: "TechRadar How-To", url: "https://www.techradar.com/how-to", keywords: ["techradar", "how to", "tech"] },
    { title: "This Old House", url: "https://www.thisoldhouse.com/", keywords: ["this old house", "home improvement", "diy"] },
    { title: "Android Central How-To", url: "https://www.androidcentral.com/how-to", keywords: ["android central", "android", "how to"] },
    { title: "Digital Trends How-To", url: "https://www.digitaltrends.com/how-to/", keywords: ["digital trends", "how to", "tech"] },
];

const HEALTH_LINKS: InternalLink[] = [...COMMON_LINKS];
const TRAVEL_LINKS: InternalLink[] = [...COMMON_LINKS];

const LIFESTYLE_LINKS: InternalLink[] = [
    ...COMMON_LINKS,
    { title: "Guardian Lifestyle", url: "https://www.theguardian.com/uk/lifeandstyle", keywords: ["guardian", "lifestyle"] },
    { title: "BuzzFeed Lifestyle", url: "https://www.buzzfeed.com/lifestyle", keywords: ["buzzfeed", "lifestyle"] },
    { title: "The Spruce Best", url: "https://www.thespruce.com/best-4139347", keywords: ["spruce", "best", "home"] },
    { title: "Esquire Gear", url: "https://www.esquire.com/gear/g3183/best-gifts/", keywords: ["esquire", "gear", "gifts"] },
    { title: "Men's Health Gear", url: "https://www.menshealth.com/gear/", keywords: ["mens health", "gear"] },
    { title: "Women's Health Gear", url: "https://www.womenshealthmag.com/gear/", keywords: ["womens health", "gear"] },
    { title: "Refinery29 Shop", url: "https://www.refinery29.com/en-us/shop", keywords: ["refinery29", "shopping"] },
    { title: "Insider Best", url: "https://www.insider.com/best", keywords: ["insider", "best"] },
    { title: "GQ Gear", url: "https://www.gq.com/story/best-of-gear", keywords: ["gq", "gear", "style"] },
    { title: "Rolling Stone Recommendations", url: "https://www.rollingstone.com/product-recommendations/", keywords: ["rolling stone", "products"] },
    { title: "Oprah Shopping", url: "https://www.oprahmag.com/shopping/gifts/", keywords: ["oprah", "shopping", "gifts"] },
];

const FINANCE_LINKS: InternalLink[] = [...COMMON_LINKS];
const EDUCATION_LINKS: InternalLink[] = [...COMMON_LINKS];
const ENTERTAINMENT_LINKS: InternalLink[] = [...COMMON_LINKS];

export const LINK_REPOSITORY: LinkRepository = {
    food: FOOD_LINKS,
    tech: TECH_LINKS,
    gaming: GAMING_LINKS,
    diy: DIY_LINKS,
    health: HEALTH_LINKS,
    travel: TRAVEL_LINKS,
    lifestyle: LIFESTYLE_LINKS,
    finance: FINANCE_LINKS,
    education: EDUCATION_LINKS,
    entertainment: ENTERTAINMENT_LINKS
};

/**
 * Helper to get links for a specific niche
 */
export const getLinksForNiche = (niche: string): InternalLink[] => {
    const normalizedNiche = niche.toLowerCase() as keyof LinkRepository;
    return LINK_REPOSITORY[normalizedNiche] || LINK_REPOSITORY.tech; // Default to tech if not found
};

/**
 * Helper to get links for a blueprint type
 */
export const getLinksForBlueprint = (blueprint: Blueprint): InternalLink[] => {
    const niche = BLUEPRINT_TO_NICHE_MAP[blueprint] || 'tech';
    return LINK_REPOSITORY[niche];
};

/**
 * Formats links for the Gemini prompt
 */
export const formatLinksForPrompt = (links: InternalLink[]): string => {
    if (!links || links.length === 0) return '';
    return links.map(link => `- ${link.title}: ${link.url} (Keywords: ${link.keywords.join(', ')})`).join('\n');
};

/**
 * List of approved external domains for outbound linking
 */
export const APPROVED_EXTERNAL_DOMAINS = [
    'wikipedia.org',
    'nytimes.com',
    'wsj.com',
    'bbc.com',
    'bbc.co.uk',
    'bbcgoodfood.com',
    'cnn.com',
    'forbes.com',
    'bloomberg.com',
    'techcrunch.com',
    'wired.com',
    'theverge.com',
    'cnet.com',
    'healthline.com',
    'webmd.com',
    'mayoclinic.org',
    'nih.gov',
    'cdc.gov',
    'who.int',
    'nationalgeographic.com',
    'scientificamerican.com',
    'nasa.gov',
    'britannica.com',
    'investopedia.com',
    'tripadvisor.com',
    'lonelyplanet.com',
    'seriouseats.com',
    'allrecipes.com',
    'foodnetwork.com',
    'bonappetit.com',
    'epicurious.com',
    'thespruceeats.com',
    'ign.com',
    'gamespot.com',
    'polygon.com',
    'kotaku.com',
    'eurogamer.net',
    'pcgamer.com',
    'consumerreports.org',
    'wirecutter.com',
    'rtings.com',
    'tomsguide.com',
    'gsmarena.com',
    'androidauthority.com',
    '9to5mac.com',
    'macrumors.com',
    'engadget.com',
    'arstechnica.com',
    'venturebeat.com',
    'mashable.com',
    'businessinsider.com',
    'hbr.org',
    'economist.com',
    'reuters.com',
    'apnews.com',
    'npr.org',
    'pbs.org',
    'smithsonianmag.com',
    'time.com',
    'usatoday.com',
    'washingtonpost.com',
    'latimes.com',
    'guardian.co.uk',
    'theguardian.com',
    'independent.co.uk',
    'telegraph.co.uk',
    'dailymail.co.uk',
    // New high-authority domains
    'goodhousekeeping.com',
    'which.co.uk',
    'bestproducts.com',
    'techradar.com',
    't3.com',
    'digitaltrends.com',
    'pcmag.com',
    'nymag.com',
    'thespruce.com',
    'trustedreviews.com',
    'soundguys.com',
    'laptopmag.com',
    'metacritic.com',
    'wikihow.com',
    'instructables.com',
    'howtogeek.com',
    'makeuseof.com',
    'lifehacker.com',
    'popularmechanics.com',
    'familyhandyman.com',
    'howstuffworks.com',
    'homedepot.com',
    'thisoldhouse.com',
    'androidcentral.com',
    'buzzfeed.com',
    'esquire.com',
    'menshealth.com',
    'womenshealthmag.com',
    'refinery29.com',
    'insider.com',
    'gq.com',
    'rollingstone.com',
    'oprahmag.com',
    'cooking.nytimes.com',
    'tasteofhome.com',
    'thekitchn.com',
    'delish.com',
    'jamieoliver.com',
    'marthastewart.com',
    'eatingwell.com',
    'bettycrocker.com',
    'cooksillustrated.com',
    'cookinglight.com',
    'thepioneerwoman.com',
    'yummly.com',
    'foodandwine.com',
    'minimalistbaker.com',
    'sallysbakingaddiction.com',
    'nigella.com',
    'olivemagazine.com',
    'tastingtable.com',
    'eater.com',
    'finecooking.com',
    'greatbritishchefs.com',
];
